language: scala
sudo: false
jdk:
  - openjdk8
scala:
  - 2.12.8
branches:
  only:
    - master
script:
  - unset _JAVA_OPTIONS
  - unset SBT_OPTS
  - travis_wait 30 sbt -Dquill.macro.log=false -J-Xms3G -J-Xmx3G -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled ";checkPR"
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete